### ISSUE TITLE
check in weblate for nonmatching format specifiers like %1

### ISSUE THREAD

**Issue by EastEriq** [koreader/koreader-translations#136]
I wonder if someone has access to the set of rules by which weblate declares that a translation string has not passed the checks. Like, presently, non matching number of line breaks, non matching closing punctuation, translation string identical to original, etc. [some of them do not necessarily point to translation errors but that's another story].
If rules could be added, I'd suggest a stricter check for the correspondence of format argument specifiers like %1, %2, etc. in both original and translation.
I ended up updating semiregularly two different localisations (one LTR and one RTL, which makes it more interesting), and I ran into a number of mismatches - like leftover orphan %1 in the translation because the original contained it in a previous version, spaced % 1, transposed 1% and such. Some are due to the suggestions of automatic translation engines which misinterpret percents; embedded bidi in the case of RTL may make more difficult to spot them. I speculate that there may be still a number of such occurrences in the various localisations, according to the samples I found. A specific rule may help.

**Comment by Frenzie** [comment]
It might be possible to set up some kind of custom regex. The current rules are all standard with Weblate.

https://docs.weblate.org/en/latest/admin/checks.html#custom-checks

**Comment by Frenzie** [comment]
Okay, this is one part of it. Now placeholders are highlighted and you can click on them to insert them in the translation.
```
placeholders:r"%[0-9 ]"
```
![Screenshot_2021-04-02_14-40-53](https://user-images.githubusercontent.com/202757/113416349-71abfc80-93c1-11eb-91b6-f41ef1a6b18a.png)

But it doesn't seem to warn about it yet. However, before looking into if there's something else still to be done, I'd like to wait until there's a translation update. It may only be detected on merge and not updated dynamically.

![Screenshot_2021-04-02_14-43-27](https://user-images.githubusercontent.com/202757/113416566-e67f3680-93c1-11eb-9e00-e88c649fabc9.png)

**Comment by EastEriq** [comment]
Thanks for looking into it. I don't know if the effort of debugging the regexp justifies the advantage, but I wanted to note this down for good, in case.

Now I do see `check:placeholders` in effect, however many are bogus. It seems for instance that also isolated % are flagged, and cases of variant singular/dual/few/many plurals are flagged too, possibly because %1 is not in all forms.
https://hosted.weblate.org/translate/koreader/koreader/it/?q=check:placeholders
https://hosted.weblate.org/translate/koreader/koreader/he/?q=check:placeholders

In any event, the check already helped me to find a couple of mistakes of the kind I wrote above.

Btw I also remember that I ran in a certain `%1s` flagged as wrong lua - _s_ there meant seconds and not a format spec.
https://hosted.weblate.org/translate/koreader/koreader/he/?offset=1&q=%251s&sort_by=-priority%2Cposition&checksum=

**Comment by Frenzie** [comment]
No debugging necessary, the problem's immediately obvious. I meant to type `%[0-9]`, not `%[0-9 ]`.

**Comment by Frenzie** [comment]
> Btw I also remember that I ran in a certain %1s flagged as wrong lua - s there meant seconds and not a format spec.

I added ignore-lua-format to the global settings now, but lua-format seems to have been added to certain strings. I'm not sure if a user did that or some automated process.

**Comment by Frenzie** [comment]
Also, hooray, we have a failing placeholders check now! :-D
![Screenshot_2021-04-02_17-30-09](https://user-images.githubusercontent.com/202757/113429606-171e9a80-93d9-11eb-8145-3ec5ceae7343.png)

**Comment by EastEriq** [comment]
Not in `it.`... https://hosted.weblate.org/translate/koreader/koreader/it/?q=Dropbox&sort_by=-priority%2Cposition&offset=6
![immagine](https://user-images.githubusercontent.com/16066531/113430379-bf852c80-93e2-11eb-94f5-e8bd962388b5.png)

At least `%[0-9]` unflagged isolated %. Now I essentially see only variant plurals flagged.

**Comment by Frenzie** [comment]
What do you mean by "not in `it.`"?

**Comment by EastEriq** [comment]
not in italian

**Comment by Frenzie** [comment]
Not in Italian what? It looks great to me.

**Comment by Frenzie** [comment]
The failing check was in Greek (which I fixed). Italian was always correct afaict.

**Comment by EastEriq** [comment]
My misunderstanding, probably. I thought your screenshot was displaying a bogus flag for either Dutch or Bokmål, and I remarked that Italian passes the check. I suppose that in the Zen view the flag meant that just one other language (Greek) had it wrong.

**Comment by Frenzie** [comment]
Ah no, it was the same screenshot as in https://github.com/koreader/koreader-translations/issues/136#issuecomment-812514260 but I could've cut it better. 

I'm not really sure if there's anything to be done about these plurals. It seems more like a Weblate issue than a config issue.

**Comment by EastEriq** [comment]
ok

**Comment by Frenzie** [comment]
I'll close this one since it's implemented. Please keep us informed! :-)
