### ISSUE TITLE
en_GB/AU?

### ISSUE THREAD

**Issue by cheywood** [koreader/koreader-translations#166]
Hello, I'm wondering if you're open to an en_GB translation? 

I jumped on Weblate to ask the same question via a submission but don't seem to be able to select en_GB there (presumably due to a setting your end?).

**Comment by Frenzie** [comment]
If you click the plus you should be able to request a new translation. But never mind that now, for I just did it myself. I imagine the bulk of the effort will be marking things as unchanged.

![image](https://github.com/koreader/koreader-translations/assets/202757/3b48696f-2162-4558-b613-7c55006859f9)

https://hosted.weblate.org/projects/koreader/koreader/en_UK/

**Comment by cheywood** [comment]
Thanks @Frenzie. I'll have a go at the en_UK changes.

> I imagine the bulk of the effort will be marking things as unchanged.

~~I'm a Weblate newbie, to mark unchanged do I just _Clone to translation_ and then uncheck _Needs editing_?~~

Edit: see below.

**Comment by cheywood** [comment]
Actually, sorry, after all that I think I'll use an offline editor and get you an MR with the `.po`.

Do you want the unchanged strings copied or left blank? Thanks.

**Comment by Frenzie** [comment]
I think the intended flow is that you duplicate it. Empty strings are always presented as needing attention. Duplicates will still ask for attention, but then you can say it's intentional. If you left the strings empty people wouldn't be able to tell them apart from ones that still require a human eye.

**Comment by cheywood** [comment]
Perfect yes that's the rational I came to too. It's a bit more obvious with (completely) different languages.

I'll have something through to you shortly.
