### ISSUE TITLE
"Turning off Wi-Fi…" in spanish wrong translated

### ISSUE THREAD

**Issue by solojohan** [koreader/koreader-translations#169]
Hi.

When you deactivate the Wi-Fi Connection you get the message "Activando wifi…".

The message should be "Desactivando wifi..."

Line 12904
https://github.com/koreader/koreader-translations/blob/5f551e92d413ccfee81c27e72a005e6c659bd036/es/koreader.po#L12904
```
#: frontend/ui/network/manager.lua:412
#: frontend/ui/network/networklistener.lua:40
msgid "Turning off Wi-Fi…"
msgstr "Activando wifi…"
```

The code should be:
```
#: frontend/ui/network/manager.lua:412
#: frontend/ui/network/networklistener.lua:40
msgid "Turning off Wi-Fi…"
msgstr "Desactivando wifi…"
```

Thanks for your work.

**Comment by Frenzie** [comment]
Changed, thanks. You can also easily do so yourself on Weblate btw. :-)

**Comment by solojohan** [comment]
That was fast!! Thanks

I didn't want to risk to mess with the translation file and I wasn't sure how githubs works (fresh user, first post, I don't know much about programming).

**Comment by Frenzie** [comment]
Not GitHub, Weblate. ;-)

https://hosted.weblate.org/projects/koreader/koreader/

It's a dedicated translation interface.
