### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by yparitcher** [koreader/koreader-translations#19]
to reflect change to weblate.

i am not sure what to write or i would make a PR

**Comment by Frenzie** [comment]
I was still thinking about that. The main text should be taken from https://github.com/koreader/koreader/pull/5722. I was planning to move it over here (i.e., to remove it from the "building" docs where it's out of place), and to link it from https://github.com/koreader/koreader/tree/0f896765c371c64d2cbefb4299f6d5658bee79b7#support or something to that effect.

What I'm less sure about is whether I want to say anything about using your own preferred apps like Lokalize, Virtaal, etc.

**Comment by yparitcher** [comment]
Great, i noticed it from there and just wanted to make sure it didnt fly under the radar :)
